name: flutter_nude_detector
description: Detect explicit content in images easily with flutter_nude_detector, a powerful Flutter package leveraging advanced machine learning for safer user experience.
version: 0.0.4+1
repository: https://github.com/piekarskipiotr/flutter-nude-detector

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_image_labeling: ^0.12.0
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0